### ISSUE TITLE
Kotlin Snippets?

### ISSUE THREAD

**Issue by the-dagger** [firebase/snippets-java#4]
@samtstern Can we have a repo for Kotlin Snippets as well?
I would be more than happy to contribute!

P.S. Sorry for off-topic discussion

**Comment by morganchen12** [comment]
IIRC this isn't on our roadmap, but ~~this~~ [the Android snippets repo](https://github.com/firebase/snippets-android) would be a good place to start measuring community interest.

Sam probably knows more details.

**Comment by jcvillalta03** [comment]
I would be interested in contributing to this if desired

**Comment by samtstern** [comment]
@the-dagger that will be in https://github.com/firebase/snippets-android

We don't really have plans to document server-side Kotlin explicitly but we do plan to do it for Android.

I actually have some kotlin snippets there right now, but they're not yet in use:
https://github.com/firebase/snippets-android/blob/master/firestore/app/src/main/java/com/google/example/firestore/kotlin/DocSnippets.kt

@jcvillalta03 if you want to contribute Kotlin snippets start by filing an issue on snippets-android about what snippets you want to convert and we can definitely discuss!

**Comment by samtstern** [comment]
Closing this here since it's on the wrong repo (but looking forward to discussing on snippets-android)

**Comment by the-dagger** [comment]
@samtstern Got it!
Just to clarify, the end goal is to convert all of Java code on https://github.com/firebase/snippets-android to Kotlin or both have to coexist?

**Comment by samtstern** [comment]
We'll have them coexist at first, similar to what we do with Swift and ObjectiveC.  Of course it's possible that some future APIs could be Kotlin-first or Kotlin-only but no plans for that so far.
